### ISSUE TITLE
Layer 1 doesn't show but Layer 0 does

### ISSUE THREAD

**Issue by sofia-m-a** [StarArawn/bevy_ecs_tilemap#134]
Here's code which gets called on setup:

```
fn layer_settings(layer_id: u16) -> LayerSettings {
    let mut l = LayerSettings::new(
        MapSize(1, 1),
        ChunkSize(CHUNK_SIZE as u32, CHUNK_SIZE as u32),
        TileSize(TILE_SIZE as f32, TILE_SIZE as f32),
        TextureSize(
            (TILE_SIZE * SHEET_W as u32) as f32,
            (TILE_SIZE * SHEET_H as u32) as f32,
        ),
    );
    l.set_layer_id(layer_id);
    l
}

// called by a setup system
pub fn generate_chunk(
    commands: &mut Commands,
    map_query: &mut MapQuery,
    texture: Handle<Image>,
    map_id: u16,
) {
    let map_entity = commands.spawn().id();
    let mut map = Map::new(map_id, map_entity);

    let (mut layer_builder_bg, layer_entity_bg) =
        LayerBuilder::new(commands, layer_settings(0u16), map_id, 0u16);
    let (mut layer_builder_fg, layer_entity_fg) =
        LayerBuilder::new(commands, layer_settings(1u16), map_id, 1u16);

    generate_island(&mut layer_builder_bg, &mut layer_builder_fg).unwrap();

    map_query.build_layer(commands, layer_builder_bg, texture.clone());
    map_query.build_layer(commands, layer_builder_fg, texture.clone());

    map.add_layer(commands, 0u16, layer_entity_bg);
    map.add_layer(commands, 1u16, layer_entity_fg);

    commands
        .entity(map_entity)
        .insert(map)
        .insert(Transform::from_xyz(-128.0, -128.0, 0.0))
        .insert(GlobalTransform::default());
}
```

generate_island only calls `LayerBuilder::set_tile`. Only the layer with layer_index 0 shows here; I'm sure it's not showing, because I've tried filling the whole layer with a particular tile and still see nothing except layer 0

**Comment by turboMaCk** [comment]
I observe the same behavior. I can see all layers if I set all of their ids to `0u16`. Anyway I also need to somehow render some of the layers above sprites for some other entities (player sprite). I looked into example which seems to do that https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/improved_iso.rs and It seems to be using these layer_ids as z_indexes. Makes me wonder if this is something that is fixed in master but is not in 0.4 release?

**Comment by turboMaCk** [comment]
@sofia-m-a With some help from @StarArawn I was able to fix the bug. In my case the problem was simply with transform of camera. Just in case your problem is similar to mine - can you please check what `transform.translation` your camera has? If your `layer_id` is higher than your camera's `transform.translation.z` than the layer appears behind the camera rather than in front of it which is why you won't be able to see it. In my case the code tracking of camera tracking of player was causing this.

**Comment by sofia-m-a** [comment]
My code has changed quite a bit since the issue, but it's fixed now and I'm pretty sure this was the cause :) so this can be closed
