### ISSUE TITLE
Feature: Isometric Staggered

### ISSUE THREAD

**Issue by martinmolin** [StarArawn/bevy_ecs_tilemap#19]
It would be really useful to be able to select Isometric Staggered or Isometric Diamond (like the current iso example) when creating a map.

For reference:
[Isometric tilemap types](https://gamedev.stackexchange.com/questions/49847/difference-between-staggered-isometric-and-normal-isometric-tilemaps)

**Comment by StarArawn** [comment]
I'm trying to wrap up some bugfixes so I don't have the time currently to add this, but I can at least point to where things are happening if you are up for making the change yourself. For example diamond iso happens here:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/render/iso-tilemap.vert#L32

You would need to duplicate the `iso-tilemap.vert` shader and call it something like: `iso-staggered-tilemap.vert`. Make the changes to the position so it outputs staggered instead of diamond. Finally create a new pipeline using the new shader and match the `IsoType` to the correct pipelines. I should be able to add this feature perhaps this weekend, but I'm not super familiar with staggered positioning of iso tiles so I would need to try and find some resources for how that is suppose to work. It kinda looks very similar to hex odd/even row positioning though.

**Comment by martinmolin** [comment]
Yep! Like you said, instead of doing:
```
position.xy *= tile_size;
```
In the shader it seems to work if you do:
```
position.x *= tile_size.x;
position.y *= tile_size.y / 2.0;
```
![bild](https://user-images.githubusercontent.com/670540/117869248-dc8f0400-b29a-11eb-85f9-3f983a32d689.png)

I can try to fork and do these changes there and make a PR that you can take a look at whenever you have time!
Thanks for the pointers 👍

**Comment by StarArawn** [comment]
The tiles look a little skewed now. I think the positioning is likely correct, but you'll want to still make sure the tiles are still scaled to `tile_size`, and only the positioning of the tile is changed.

**Comment by martinmolin** [comment]
Yep you're right! Good catch 😄

**Comment by martinmolin** [comment]
After a bit of fiddling I ended up with:
![bild](https://user-images.githubusercontent.com/670540/117877996-8d020580-b2a5-11eb-93af-66c6cfee6948.png)

I'll make a PR and you can check it whenever!

**Comment by ekaats** [comment]
Related to this, I have been trying to add hills like on the 4th row in the iso.png tilesheet and have ran into some issues. The tilesize in iso.rs is defined as 64x32 which works well for the flat tiles, but for those that are higher. I suspect the tiles should actually be loaded as 64x64 and placed in the correct pattern in the pipeline.

I haven't had the chance to take a further look at that, but I'll try to do so tomorrow. Does this sound like it makes sense or am I misunderstanding something?

**Comment by StarArawn** [comment]
> Related to this, I have been trying to add hills like on the 4th row in the iso.png tilesheet and have ran into some issues. The tilesize in iso.rs is defined as 64x32 which works well for the flat tiles, but for those that are higher. I suspect the tiles should actually be loaded as 64x64 and placed in the correct pattern in the pipeline.
> 
> I haven't had the chance to take a further look at that, but I'll try to do so tomorrow. Does this sound like it makes sense or am I misunderstanding something?

Currently there is an issue with tile uv's I'll try to fix it for ISO in a little bit today.

**Comment by StarArawn** [comment]
Closing this issue since the work is merged in.
