### ISSUE TITLE
Unwrap() in extract.rs is panicking 

### ISSUE THREAD

**Issue by Affinator** [StarArawn/bevy_ecs_tilemap#303]
After a "cargo update" and then changing all TilemapTextures to TilemapTexture::Single I get the following error on formerly working code:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryDoesNotMatch(3v0)', /home/xxxxxxx/.cargo/git/checkouts/bevy_ecs_tilemap-8c720d5970222b21/eabd66e/src/render/extract.rs:254:52

**Comment by bzm3r** [comment]
@Affinator hmm, do you think there is a minimal example you could share with us that reproduces this issue? I want to fix it ASAP.

I thought I saw something like this in the past, and that I fixed it, but apparently not.

**Comment by bzm3r** [comment]
@Affinator Also, are you using the `atlas` feature or not?

**Comment by bzm3r** [comment]
The query that is being marked as a problem is this one: https://github.com/StarArawn/bevy_ecs_tilemap/blob/eabd66eac4c5204ec54646141ffb26935cace88d/src/render/extract.rs#L179

In particular, the call here is panicking: https://github.com/StarArawn/bevy_ecs_tilemap/blob/eabd66eac4c5204ec54646141ffb26935cace88d/src/render/extract.rs#L254

So, this is not like the other issue I fixed, which was around the draw commands not finding the entities they were looking for. 

This instead has to do with not finding the tilemap requested based on the tilemap id that was provided...

A minimal not-working example would be super useful, because it is hard to otherwise understand this issue when the examples are all working :/

**Comment by Affinator** [comment]
Found it: The query was not getting my tilemaps, due to a missing FrustumCulling component (I had an old self made bundle for the tilemaps still in my code...)
