### ISSUE TITLE
Best way to destroy and recreate a tilemap?

### ISSUE THREAD

**Issue by OwlyCode** [StarArawn/bevy_ecs_tilemap#454]
Hello and thank you for this awesome crate!

I'm encountering an issue with the 0.11 version while attempting to make a save system:

I've an exclusive system that removes all the entities (including tiles and tilemap) and then spawns a new tilemap with fresh storage and tiles. It all runs in a specific state. It works fine but however I randomly get the following messages in the log:

```
Failed to 'insert or spawn' bundle of type bevy_ecs_tilemap::render::extract::ExtractedTilemapTextureBundle into the following invalid entities: [374v2]
```

Am I doing something wrong? Is this a bug?

**Comment by rparrett** [comment]
I'm going to close this because after version `0.15` so much has changed in the related code that it seems unlikely that this precise bug could still be present. Please feel free to open a new issue.

We also just added a new `spawn_and_despawn_tilemap` example.

Sorry for the very long delay in responding.
