### ISSUE TITLE
Orientation for Tiled Hexagon map off?

### ISSUE THREAD

**Issue by soft-circles** [StarArawn/bevy_ecs_tilemap#462]
I created a Hexagon map in Tiled with a staggered odd index:

<img width="338" alt="Screenshot 2023-08-21 at 5 38 16 PM" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/4955407/d21e77db-d705-46ee-ad5b-1e5a0f85245a">
<img width="414" alt="Screenshot 2023-08-21 at 5 38 22 PM" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/4955407/5779d3aa-624b-4cf0-94fe-edebc023343e">

And when I convert the layout with the bevy_ecs_tilemap in `helpers/tiled.rs` ([code](https://github.com/StarArawn/bevy_ecs_tilemap/blob/fbda80c735bf7faaa2cc4d79524cfbf016044a0f/examples/helpers/tiled.rs#L290)) the map appears incorrectly if I define the `HexCoordSystem` as `ColumnOdd`.

<img width="300" alt="Screenshot 2023-08-21 at 5 38 35 PM" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/4955407/c7116c18-ba41-48ef-903f-4135336c6ca4">

It appears correctly if I define the `HexCoordSystem` as `ColumnEven`:

<img width="313" alt="Screenshot 2023-08-21 at 6 01 37 PM" src="https://github.com/StarArawn/bevy_ecs_tilemap/assets/4955407/4e354aad-976f-416e-bd06-963bf2824417">

**Comment by rparrett** [comment]
I think this behavior is somewhat "expected" because Bevy's y-axis is inverted relative to Tiled.

This was brought up previously in a stalled out PR that added support for `StaggerAxis` / `StaggerIndex` https://github.com/StarArawn/bevy_ecs_tilemap/pull/405#discussion_r1148564979 to that example, and the consensus seemed to be that it's correct to use the opposite index for column stagger when building the tilemap.

**Comment by StarArawn** [comment]
This appears to be an asset loading error with tiled. Please remember that the tiled example is only meant to be a minimal example of how to use tiled with `bevy_ecs_tilemap` as such we'll not be expanding features to support things like this.
