### ISSUE TITLE
Incorrect usage of rs-tiled

### ISSUE THREAD

**Issue by feelingsonice** [StarArawn/bevy_ecs_tilemap#502]
I'm running into the same issue specified here on rs-tiled, someone else ran into it earlier -- https://github.com/mapeditor/rs-tiled/issues/265

The issue is explained via this comment https://github.com/mapeditor/rs-tiled/issues/265#issuecomment-1537367368

I don't think this has been fixed since.

**Comment by zetsub0u** [comment]
seeing the same thing with latest version of everything

**Comment by StarArawn** [comment]
The example is meant to only serve as a short example of how one "might" implement tiled loading. Its not meant to be feature complete or bug proof. As long as the examples load/run that is enough. I'm happy to help someone build a crate specifically for loading tiled maps with `bevy_ecs_tilemap` as I have experience doing it.

**Comment by meisei4** [comment]
_Disclaimer:  I am a beginner to open source, as well as rust and bevy_

Very sorry to bring this up again🙇‍♂️, but I was wondering what the current state of this issue is? 

From the Feb 11th comment, is it correct in understanding that there is no "official way" to load the .tmx, .tsx files using `bevy_ecs_tilemap`? for example I am currently trying to load a tiled map that is made up of the following [.tmx, .tsx, .png file](https://github.com/meisei4/yakuzaishi/tree/master/assets/map_data), where i have copy and pasted the [helpers/tiled.rs](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/helpers/tiled.rs) into my beginner bevy migration project and am trying to use this projects [tiled.rs example](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/tiled.rs) in [exactly the same way](https://github.com/meisei4/yakuzaishi/blob/bevy_migration/src/startup/bevy_ecs_tilemap_initial_render_system.rs)

but I am still getting the same `Missing attribute: tilecount` as what is explained in the original issue [mapeditor/rs-tiled/issues/265](https://github.com/mapeditor/rs-tiled/issues/265)

I would love to participate in any investigation of this issue and any way i can help maybe think of a solution? But as a beginner here i am hoping to first learn the current state of the issue, and how other people might be solving it in custom ways? (I cant seem to find any examples of solutions for it that I can replicate)

**Comment by StarArawn** [comment]
> Very sorry to bring this up again🙇‍♂️, but I was wondering what the current state of this issue is?

The current status is that it wont be fixed. I'm happy to work with someone to create a `bevy_rs_tiled` crate but I don't have the time to do this myself.

> From the Feb 11th comment, is it correct in understanding that there is no "official way" to load the .tmx, .tsx files using `bevy_ecs_tilemap`? 

Correct

> for example I am currently trying to load a tiled map that is made up of the following [.tmx, .tsx, .png file](https://github.com/meisei4/yakuzaishi/tree/master/assets/map_data), where i have copy and pasted the [helpers/tiled.rs](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/helpers/tiled.rs) into my beginner bevy migration project and am trying to use this projects [tiled.rs example](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/tiled.rs) in [exactly the same way](https://github.com/meisei4/yakuzaishi/blob/bevy_migration/src/startup/bevy_ecs_tilemap_initial_render_system.rs)
> 

You can use the tiled example as a started to build something more but it's not intended to be useful out of the box and will require work to make functional in your own apps.

> (also I am using a branch solution that i found from the bevy discord help channel that imports bevy_ecs_tilemap as follows:
> 
> `bevy_ecs_tilemap = { git = "https://github.com/rparrett/bevy_ecs_tilemap", branch = "bevy13" }`

This is old information that is no longer correct since the bevy13 branch has been merged instead you should be using:
`bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main" }`
 
> I would love to participate in any investigation of this issue and any way i can help maybe think of a solution? But as a beginner here i am hoping to first learn the current state of the issue, and how other people might be solving it in custom ways? (I cant seem to find any examples of solutions for it that I can replicate)

If a tiled map loader is your goal the best way to help would be to start a new crate for loading these files in bevy. Ideally you would want to start by looking at how rs-tiled works, what data is expected, and look at the tiled.rs example here as a way of getting started. From there you could slowly add new features based on the tiled map editor spec. Its quite detailed and can be found here:
https://doc.mapeditor.org/en/stable/
